version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs: 
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}-<< parameters.node-version >>
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}-<< parameters.node-version >>
          paths: 
            - node_modules
            - package-lock.json 
      - run:
          name: Run test using nodejs << parameters.node-version >>
          command: npm start
  push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:27:23:ab:01:73:4e:bb:a1:6f:24:c1:8b:5c:54:5f"
      - checkout
      - run: 
          name: Clone repo
          command: git clone --mirror https://github.com/Assabiq31213/JessicaMd.git
      - run:
          name: Change directory & Remote mirror repo & Update repo &
          command: cd JessicaMd.git &&
                  git remote set-url --push origin https://github.com/Assabiq31213/JessicaMd.gitt && 
                  git fetch -p origin &&
                  (git push --mirror || exit 0)
workflows:
  all-test:
    jobs:
      - test: 
          matrix:
            parameters:
              node-version: ['14.19', '16.14', '17.5']
  push-to-mirror:
    jobs:
      - push:
          filters:
            branches:
              only:
                - master
